combination_sizes:
- 5
global_features:
  Head_angular_acceleration_x:
    features:
    - Head_angular_acceleration_x
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  Head_angular_acceleration_y:
    features:
    - Head_angular_acceleration_y
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  Head_angular_acceleration_z:
    features:
    - Head_angular_acceleration_z
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  Head_angular_velocity_x:
    features:
    - Head_angular_velocity_x
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  Head_angular_velocity_y:
    features:
    - Head_angular_velocity_y
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  Head_angular_velocity_z:
    features:
    - Head_angular_velocity_z
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  Head_euler_x:
    features:
    - Head_euler_x
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  Head_euler_y:
    features:
    - Head_euler_y
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  Head_euler_z:
    features:
    - Head_euler_z
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  Head_position_x:
    features:
    - Head_position_x
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  Head_position_y:
    features:
    - Head_position_y
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  Head_position_z:
    features:
    - Head_position_z
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  Head_velocity_x:
    features:
    - Head_velocity_x
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  Head_velocity_y:
    features:
    - Head_velocity_y
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  Head_velocity_z:
    features:
    - Head_velocity_z
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  LeftHand_angular_acceleration_x:
    features:
    - LeftHand_angular_acceleration_x
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  LeftHand_angular_acceleration_y:
    features:
    - LeftHand_angular_acceleration_y
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  LeftHand_angular_acceleration_z:
    features:
    - LeftHand_angular_acceleration_z
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  LeftHand_angular_velocity_x:
    features:
    - LeftHand_angular_velocity_x
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  LeftHand_angular_velocity_y:
    features:
    - LeftHand_angular_velocity_y
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  LeftHand_angular_velocity_z:
    features:
    - LeftHand_angular_velocity_z
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  LeftHand_euler_x:
    features:
    - LeftHand_euler_x
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  LeftHand_euler_y:
    features:
    - LeftHand_euler_y
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  LeftHand_euler_z:
    features:
    - LeftHand_euler_z
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  LeftHand_position_x:
    features:
    - LeftHand_position_x
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  LeftHand_position_y:
    features:
    - LeftHand_position_y
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  LeftHand_position_z:
    features:
    - LeftHand_position_z
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  LeftHand_velocity_x:
    features:
    - LeftHand_velocity_x
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  LeftHand_velocity_y:
    features:
    - LeftHand_velocity_y
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  LeftHand_velocity_z:
    features:
    - LeftHand_velocity_z
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  RightHand_angular_acceleration_x:
    features:
    - RightHand_angular_acceleration_x
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  RightHand_angular_acceleration_y:
    features:
    - RightHand_angular_acceleration_y
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  RightHand_angular_acceleration_z:
    features:
    - RightHand_angular_acceleration_z
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  RightHand_angular_velocity_x:
    features:
    - RightHand_angular_velocity_x
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  RightHand_angular_velocity_y:
    features:
    - RightHand_angular_velocity_y
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  RightHand_angular_velocity_z:
    features:
    - RightHand_angular_velocity_z
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  RightHand_euler_x:
    features:
    - RightHand_euler_x
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  RightHand_euler_y:
    features:
    - RightHand_euler_y
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  RightHand_euler_z:
    features:
    - RightHand_euler_z
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  RightHand_position_x:
    features:
    - RightHand_position_x
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  RightHand_position_y:
    features:
    - RightHand_position_y
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  RightHand_position_z:
    features:
    - RightHand_position_z
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  RightHand_velocity_x:
    features:
    - RightHand_velocity_x
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  RightHand_velocity_y:
    features:
    - RightHand_velocity_y
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
  RightHand_velocity_z:
    features:
    - RightHand_velocity_z
    statistics:
    - median
    - mean
    - min
    - max
    - std
    transform: none
metadata_fields:
- Gender
- Hand
- A_Build_Time
- B_Build_Time
required_global_features:
- LeftHand_euler_x_max
- Head_euler_z_std
- RightHand_euler_z_std
- RightHand_angular_acceleration_z_std
