cls_score_threshold: 0
cross_task: true
dataset: v3
export_feature_table: false
feature_selection_measure: mcc
inner_cv_k: 5
inner_cv_repeats: 2
nan_policy: impute
outer_cv_k: null
predictor_type: classification
random_state: 42
run_mode: manual
sample_rates: null
score_type: _Linear
segment_policy: full
train_policy: B
