  Head_position_x:
   features: [Head_position_x]
   statistics: [median, mean]
   transform: none
  Head_position_y:
   features: [Head_position_y]
   statistics: [median, mean]
   transform: none
  Head_position_z:
   features: [Head_position_z]
   statistics: [median, mean]
   transform: none
  Head_sixD_a:
   features: [Head_sixD_a]
   statistics: [median, mean]
   transform: none
  Head_sixD_b:
   features: [Head_sixD_b]
   statistics: [median, mean]
   transform: none
  Head_sixD_c:
   features: [Head_sixD_c]
   statistics: [median, mean]
   transform: none
  Head_sixD_d:
   features: [Head_sixD_d]
   statistics: [median, mean]
   transform: none
  Head_sixD_e:
   features: [Head_sixD_e]
   statistics: [median, mean]
   transform: none
  Head_sixD_f:
   features: [Head_sixD_f]
   statistics: [median, mean]
   transform: none
  LeftHand_position_x:
   features: [LeftHand_position_x]
   statistics: [median, mean]
   transform: none
  LeftHand_position_y:
   features: [LeftHand_position_y]
   statistics: [median, mean]
   transform: none
  LeftHand_position_z:
   features: [LeftHand_position_z]
   statistics: [median, mean]
   transform: none
  LeftHand_sixD_a:
   features: [LeftHand_sixD_a]
   statistics: [median, mean]
   transform: none
  LeftHand_sixD_b:
   features: [LeftHand_sixD_b]
   statistics: [median, mean]
   transform: none
  LeftHand_sixD_c:
   features: [LeftHand_sixD_c]
   statistics: [median, mean]
   transform: none
  LeftHand_sixD_d:
   features: [LeftHand_sixD_d]
   statistics: [median, mean]
   transform: none
  LeftHand_sixD_e:
   features: [LeftHand_sixD_e]
   statistics: [median, mean]
   transform: none
  LeftHand_sixD_f:
   features: [LeftHand_sixD_f]
   statistics: [median, mean]
   transform: none
  RightHand_position_x:
   features: [RightHand_position_x]
   statistics: [median, mean]
   transform: none
  RightHand_position_y:
   features: [RightHand_position_y]
   statistics: [median, mean]
   transform: none
  RightHand_position_z:
   features: [RightHand_position_z]
   statistics: [median, mean]
   transform: none
  RightHand_sixD_a:
   features: [RightHand_sixD_a]
   statistics: [median, mean]
   transform: none
  RightHand_sixD_b:
   features: [RightHand_sixD_b]
   statistics: [median, mean]
   transform: none
  RightHand_sixD_c:
   features: [RightHand_sixD_c]
   statistics: [median, mean]
   transform: none
  RightHand_sixD_d:
   features: [RightHand_sixD_d]
   statistics: [median, mean]
   transform: none
  RightHand_sixD_e:
   features: [RightHand_sixD_e]
   statistics: [median, mean]
   transform: none
  RightHand_sixD_f:
   features: [RightHand_sixD_f]
   statistics: [median, mean]
   transform: none
  Head_euler_x:
   features: [Head_euler_x]
   statistics: [median, mean]
   transform: none
  Head_euler_y:
   features: [Head_euler_y]
   statistics: [median, mean]
   transform: none
  Head_euler_z:
   features: [Head_euler_z]
   statistics: [median, mean]
   transform: none
  LeftHand_euler_x:
   features: [LeftHand_euler_x]
   statistics: [median, mean]
   transform: none
  LeftHand_euler_y:
   features: [LeftHand_euler_y]
   statistics: [median, mean]
   transform: none
  LeftHand_euler_z:
   features: [LeftHand_euler_z]
   statistics: [median, mean]
   transform: none
  RightHand_euler_x:
   features: [RightHand_euler_x]
   statistics: [median, mean]
   transform: none
  RightHand_euler_y:
   features: [RightHand_euler_y]
   statistics: [median, mean]
   transform: none
  RightHand_euler_z:
   features: [RightHand_euler_z]
   statistics: [median, mean]  
  Head_acceleration_x:
   features: [Head_acceleration_x]
   statistics: [median, mean]
   transform: none
  Head_acceleration_y:
   features: [Head_acceleration_y]
   statistics: [median, mean]
   transform: none
  Head_acceleration_z:
   features: [Head_acceleration_z]
   statistics: [median, mean]
   transform: none
  Head_jerk_x:
   features: [Head_jerk_x]
   statistics: [median, mean]
   transform: none
  Head_jerk_y:
   features: [Head_jerk_y]
   statistics: [median, mean]
   transform: none
  Head_jerk_z:
   features: [Head_jerk_z]
   statistics: [median, mean]
   transform: none
  Head_angular_velocity_x:
   features: [Head_angular_velocity_x]
   statistics: [median, mean]
   transform: none
  Head_angular_velocity_y:
   features: [Head_angular_velocity_y]
   statistics: [median, mean]
   transform: none
  Head_angular_velocity_z:
   features: [Head_angular_velocity_z]
   statistics: [median, mean]
   transform: none
  Head_angular_acceleration_x:
   features: [Head_angular_acceleration_x]
   statistics: [median, mean]
   transform: none
  Head_angular_acceleration_y:
   features: [Head_angular_acceleration_y]
   statistics: [median, mean]
   transform: none
  Head_angular_acceleration_z:
   features: [Head_angular_acceleration_z]
   statistics: [median, mean]
   transform: none
  Head_angular_jerk_x:
   features: [Head_angular_jerk_x]
   statistics: [median, mean]
   transform: none
  Head_angular_jerk_y:
   features: [Head_angular_jerk_y]
   statistics: [median, mean]
   transform: none
  Head_angular_jerk_z:
   features: [Head_angular_jerk_z]
   statistics: [median, mean]  
  Head_acceleration_x:
   features: [Head_acceleration_x]
   statistics: [median, mean]
   transform: none
  Head_acceleration_y:
   features: [Head_acceleration_y]
   statistics: [median, mean]
   transform: none
  Head_acceleration_z:
   features: [Head_acceleration_z]
   statistics: [median, mean]
   transform: none
  Head_jerk_x:
   features: [Head_jerk_x]
   statistics: [median, mean]
   transform: none
  Head_jerk_y:
   features: [Head_jerk_y]
   statistics: [median, mean]
   transform: none
  Head_jerk_z:
   features: [Head_jerk_z]
   statistics: [median, mean]
   transform: none
  Head_angular_velocity_x:
   features: [Head_angular_velocity_x]
   statistics: [median, mean]
   transform: none
  Head_angular_velocity_y:
   features: [Head_angular_velocity_y]
   statistics: [median, mean]
   transform: none
  Head_angular_velocity_z:
   features: [Head_angular_velocity_z]
   statistics: [median, mean]
   transform: none
  Head_angular_acceleration_x:
   features: [Head_angular_acceleration_x]
   statistics: [median, mean]
   transform: none
  Head_angular_acceleration_y:
   features: [Head_angular_acceleration_y]
   statistics: [median, mean]
   transform: none
  Head_angular_acceleration_z:
   features: [Head_angular_acceleration_z]
   statistics: [median, mean]
   transform: none
  Head_angular_jerk_x:
   features: [Head_angular_jerk_x]
   statistics: [median, mean]
   transform: none
  Head_angular_jerk_y:
   features: [Head_angular_jerk_y]
   statistics: [median, mean]
   transform: none
  Head_angular_jerk_z:
   features: [Head_angular_jerk_z]
   statistics: [median, mean]
   transform: none
  LeftHand_acceleration_x:
   features: [LeftHand_acceleration_x]
   statistics: [median, mean]
   transform: none
  LeftHand_acceleration_y:
   features: [LeftHand_acceleration_y]
   statistics: [median, mean]
   transform: none
  LeftHand_acceleration_z:
   features: [LeftHand_acceleration_z]
   statistics: [median, mean]
   transform: none
  LeftHand_jerk_x:
   features: [LeftHand_jerk_x]
   statistics: [median, mean]
   transform: none
  LeftHand_jerk_y:
   features: [LeftHand_jerk_y]
   statistics: [median, mean]
   transform: none
  LeftHand_jerk_z:
   features: [LeftHand_jerk_z]
   statistics: [median, mean]
   transform: none
  LeftHand_angular_velocity_x:
   features: [LeftHand_angular_velocity_x]
   statistics: [median, mean]
   transform: none
  LeftHand_angular_velocity_y:
   features: [LeftHand_angular_velocity_y]
   statistics: [median, mean]
   transform: none
  LeftHand_angular_velocity_z:
   features: [LeftHand_angular_velocity_z]
   statistics: [median, mean]
   transform: none
  LeftHand_angular_acceleration_x:
   features: [LeftHand_angular_acceleration_x]
   statistics: [median, mean]
   transform: none
  LeftHand_angular_acceleration_y:
   features: [LeftHand_angular_acceleration_y]
   statistics: [median, mean]
   transform: none
  LeftHand_angular_acceleration_z:
   features: [LeftHand_angular_acceleration_z]
   statistics: [median, mean]
   transform: none
  LeftHand_angular_jerk_x:
   features: [LeftHand_angular_jerk_x]
   statistics: [median, mean]
   transform: none
  LeftHand_angular_jerk_y:
   features: [LeftHand_angular_jerk_y]
   statistics: [median, mean]
   transform: none
  LeftHand_angular_jerk_z:
   features: [LeftHand_angular_jerk_z]
   statistics: [median, mean]
   transform: none
  RightHand_acceleration_x:
   features: [RightHand_acceleration_x]
   statistics: [median, mean]
   transform: none
  RightHand_acceleration_y:
   features: [RightHand_acceleration_y]
   statistics: [median, mean]
   transform: none
  RightHand_acceleration_z:
   features: [RightHand_acceleration_z]
   statistics: [median, mean]
   transform: none
  RightHand_jerk_x:
   features: [RightHand_jerk_x]
   statistics: [median, mean]
   transform: none
  RightHand_jerk_y:
   features: [RightHand_jerk_y]
   statistics: [median, mean]
   transform: none
  RightHand_jerk_z:
   features: [RightHand_jerk_z]
   statistics: [median, mean]
   transform: none
  RightHand_angular_velocity_x:
   features: [RightHand_angular_velocity_x]
   statistics: [median, mean]
   transform: none
  RightHand_angular_velocity_y:
   features: [RightHand_angular_velocity_y]
   statistics: [median, mean]
   transform: none
  RightHand_angular_velocity_z:
   features: [RightHand_angular_velocity_z]
   statistics: [median, mean]
   transform: none
  RightHand_angular_acceleration_x:
   features: [RightHand_angular_acceleration_x]
   statistics: [median, mean]
   transform: none
  RightHand_angular_acceleration_y:
   features: [RightHand_angular_acceleration_y]
   statistics: [median, mean]
   transform: none
  RightHand_angular_acceleration_z:
   features: [RightHand_angular_acceleration_z]
   statistics: [median, mean]
   transform: none
  RightHand_angular_jerk_x:
   features: [RightHand_angular_jerk_x]
   statistics: [median, mean]
   transform: none
  RightHand_angular_jerk_y:
   features: [RightHand_angular_jerk_y]
   statistics: [median, mean]
   transform: none
  RightHand_angular_jerk_z:
   features: [RightHand_angular_jerk_z]
   statistics: [median, mean]
   transform: none
  Head_velocity_pause_duration:
   features: [Head_velocity_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  Head_velocity_time_since_pause:
   features: [Head_velocity_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  Head_acceleration_pause_duration:
   features: [Head_acceleration_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  Head_acceleration_time_since_pause:
   features: [Head_acceleration_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  Head_jerk_pause_duration:
   features: [Head_jerk_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  Head_jerk_time_since_pause:
   features: [Head_jerk_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  Head_angular_velocity_pause_duration:
   features: [Head_angular_velocity_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  Head_angular_velocity_time_since_pause:
   features: [Head_angular_velocity_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  Head_angular_acceleration_pause_duration:
   features: [Head_angular_acceleration_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  Head_angular_acceleration_time_since_pause:
   features: [Head_angular_acceleration_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  Head_angular_jerk_pause_duration:
   features: [Head_angular_jerk_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  Head_angular_jerk_time_since_pause:
   features: [Head_angular_jerk_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  LeftHand_velocity_pause_duration:
   features: [LeftHand_velocity_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  LeftHand_velocity_time_since_pause:
   features: [LeftHand_velocity_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  LeftHand_acceleration_pause_duration:
   features: [LeftHand_acceleration_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  LeftHand_acceleration_time_since_pause:
   features: [LeftHand_acceleration_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  LeftHand_jerk_pause_duration:
   features: [LeftHand_jerk_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  LeftHand_jerk_time_since_pause:
   features: [LeftHand_jerk_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  LeftHand_angular_velocity_pause_duration:
   features: [LeftHand_angular_velocity_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  LeftHand_angular_velocity_time_since_pause:
   features: [LeftHand_angular_velocity_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  LeftHand_angular_acceleration_pause_duration:
   features: [LeftHand_angular_acceleration_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  LeftHand_angular_acceleration_time_since_pause:
   features: [LeftHand_angular_acceleration_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  LeftHand_angular_jerk_pause_duration:
   features: [LeftHand_angular_jerk_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  LeftHand_angular_jerk_time_since_pause:
   features: [LeftHand_angular_jerk_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  RightHand_velocity_pause_duration:
   features: [RightHand_velocity_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  RightHand_velocity_time_since_pause:
   features: [RightHand_velocity_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  RightHand_acceleration_pause_duration:
   features: [RightHand_acceleration_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  RightHand_acceleration_time_since_pause:
   features: [RightHand_acceleration_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  RightHand_jerk_pause_duration:
   features: [RightHand_jerk_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  RightHand_jerk_time_since_pause:
   features: [RightHand_jerk_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  RightHand_angular_velocity_pause_duration:
   features: [RightHand_angular_velocity_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  RightHand_angular_velocity_time_since_pause:
   features: [RightHand_angular_velocity_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  RightHand_angular_acceleration_pause_duration:
   features: [RightHand_angular_acceleration_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  RightHand_angular_acceleration_time_since_pause:
   features: [RightHand_angular_acceleration_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  RightHand_angular_jerk_pause_duration:
   features: [RightHand_angular_jerk_pause_duration]
   statistics: [min, max, median, mean]
   transform: none
  RightHand_angular_jerk_time_since_pause:
   features: [RightHand_angular_jerk_time_since_pause]
   statistics: [min, max, median, mean]
   transform: none
  Head_quat_x:
   features: [Head_quat_x]
   statistics: [median, mean, min, max]
   transform: none
  Head_quat_y:
   features: [Head_quat_y]
   statistics: [median, mean, min, max]
   transform: none
  Head_quat_z:
   features: [Head_quat_z]
   statistics: [median, mean, min, max]
   transform: none
  Head_quat_w:
   features: [Head_quat_w]
   statistics: [median, mean, min, max]
   transform: none
  LeftHand_quat_x:
   features: [LeftHand_quat_x]
   statistics: [median, mean, min, max]
   transform: none
  LeftHand_quat_y:
   features: [LeftHand_quat_y]
   statistics: [median, mean, min, max]
   transform: none
  LeftHand_quat_z:
   features: [LeftHand_quat_z]
   statistics: [median, mean, min, max]
   transform: none
  LeftHand_quat_w:
   features: [LeftHand_quat_w]
   statistics: [median, mean, min, max]
   transform: none
  RightHand_quat_x:
   features: [RightHand_quat_x]
   statistics: [median, mean, min, max]
   transform: none
  RightHand_quat_y:
   features: [RightHand_quat_y]
   statistics: [median, mean, min, max]
   transform: none
  RightHand_quat_z:
   features: [RightHand_quat_z]
   statistics: [median, mean, min, max]
   transform: none
  RightHand_quat_w:
   features: [RightHand_quat_w]
   statistics: [median, mean, min, max]
   transform: none