model:
  type: 'knn'  # 'knn', 'random_forest', 'svm', 'linear_svm', 'tabpfn', 'logistic', 'lightgbm', or 'mlp'
  
  use_resampling: false
  resampling_strategy: 'none'  # Options: 'smote_tomek', 'none'

  # Parameter grids for nested CV
  param_grids:
    knn:
      n_neighbors: [5, 9, 19]
      weights: ['uniform']
      metric: ['euclidean']
    
    random_forest:
      n_estimators: [25, 50, 100]
      max_depth: [10, 25, 50, 100, None]
      min_samples_split: [2, 5, 10]
      min_samples_leaf: [1, 2, 5, 10]
    
    lightgbm:
      n_estimators: [50, 100, 200]
      max_depth: [3, 5, 7]
      num_leaves: [31, 50, 100]
      learning_rate: [0.01, 0.1, 1]
      min_samples_leaf: [1, 2, 5, 10]
    
    svm:
      C: [0.1, 1, 10]
      kernel: ['linear', 'rbf', 'poly']
      gamma: ['scale', 'auto']
    
    mlp:
      hidden_layer_sizes: [[50], [100], [50, 25], [100, 50]]
      activation: ['relu', 'tanh']
      learning_rate_init: [0.001, 0.01]
      max_iter: [1000]

  # Base model parameters (for non-nested CV experiments)
  model_params:
    knn:
      n_neighbors: 5
      weights: 'uniform'
      n_jobs: 1
    
    random_forest:
      n_estimators: 100
      n_jobs: 1
    
    svm:
      kernel: 'poly'
      probability: true
    
    lightgbm:
      n_estimators: 100
      n_jobs: 1
      verbosity: -1