export_feature_table: false

nan_policy: impute # impute, drop

train_policy: A # A, B

score_type: '_Linear' # '_Linear', ''

segment_policy: full

sample_rates: null

dataset: 'v3' # 'v3', 'BodyRelative_Motion_PQ'

predictor_type: 'classification'

run_mode: 'manual' # 'automatic', 'manual'

feature_selection_measure: 'mcc' # 'specificity', 'f1', 'accuracy', 'balanced_accuracy', 'mcc'

cross_task: false # true, false

random_state: 42

inner_cv_k: 4

inner_cv_repeats: 2

outer_cv_k: 5 # always 1 on cross_task true

cls_score_threshold: 0 # 0, 4, 6, 8